#To remove warning
spring:
  jpa:
    open-in-view: false
#For Spring to find RSAng
rsa:
  private-key: classpath:certificates/private_key.pem
  public-key: classpath:certificates/public_key.pem
#Enabling Security loging for debug purposes
logging:
  level:
    org.springframework.security: DEBUG
